[ProjectSettings]
GameID=DEEDAAB94925C0C184610D9C69436D21

[Engine.WorldInfo]
;GlobalDefaultGameType="BendGame.BendGameMode"

[/Script/BendGame.BendGameMission]
;StartGameAtMissionOverride=CRW-DEMO

[/Script/BendGame.BendGameMode]
;PlayerLocationOverride=(X=-76284.0,Y=-222321.0,Z=-5554.84961)
;PlayerRotationOverride=(Pitch=0.0,Yaw=157.499023,Roll=0.0)

[/Script/Engine.WorldSettings]
-EnabledPlugins="ExampleDeviceProfileSelector"

[/Script/EngineSettings.GeneralProjectSettings]
CompanyName=
CompanyName=BendStudio
ProjectID=00000000000000000000000000000000
ProjectName=Project Red Chair
ProjectDisplayedTitle=Days Gone

[/Script/GameplayAbilities.AbilitySystemGlobals]
GlobalCurveTableName=/Game/Libraries/Tuning/Attributes/Attributes_GlobalCurveTable.Attributes_GlobalCurveTable
GlobalAttributeMetaDataTableName=/Game/Libraries/Tuning/Attributes/Attributes_MetaDataTable.Attributes_MetaDataTable
GlobalAttributeSetDefaultsTableName=/Game/Libraries/Tuning/Attributes/Attributes_SetDefaultsTable.Attributes_SetDefaultsTable

[/Script/Engine.PlayerController]
InputYawScale=1.0
InputPitchScale=-1.0
InputRollScale=1.0

[/Script/BendGame.BendPlayerController]
StartPlayerWithRandomWeapon=True

[/Script/BendGame.InventoryItemManager]
InventoryManagerClassReference=/Game/Libraries/Blueprints/Inventory/Items/BP_InventoryItemMgr.BP_InventoryItemMgr_C

[/Script/BendGame.BendAITeamSettings]
TeamSystemClassReference=/Game/Libraries/Blueprints/AI/TeamSystem/TeamSystem.TeamSystem_C
+TeamClassReferences=/Game/Libraries/Blueprints/AI/TeamSystem/Teams/BearTeam.BearTeam_C
+TeamClassReferences=/Game/Libraries/Blueprints/AI/TeamSystem/Teams/CannibalTeam.CannibalTeam_C
+TeamClassReferences=/Game/Libraries/Blueprints/AI/TeamSystem/Teams/CopelandTeam.CopelandTeam_C
+TeamClassReferences=/Game/Libraries/Blueprints/AI/TeamSystem/Teams/CougarTeam.CougarTeam_C
+TeamClassReferences=/Game/Libraries/Blueprints/AI/TeamSystem/Teams/CrowTeam.CrowTeam_C
+TeamClassReferences=/Game/Libraries/Blueprints/AI/TeamSystem/Teams/DeerTeam.DeerTeam_C
+TeamClassReferences=/Game/Libraries/Blueprints/AI/TeamSystem/Teams/FreakerCougarTeam.FreakerCougarTeam_C
+TeamClassReferences=/Game/Libraries/Blueprints/AI/TeamSystem/Teams/FreakerCrowTeam.FreakerCrowTeam_C
+TeamClassReferences=/Game/Libraries/Blueprints/AI/TeamSystem/Teams/HotSpringsTeam.HotspringsTeam_C
+TeamClassReferences=/Game/Libraries/Blueprints/AI/TeamSystem/Teams/IronMikesTeam.IronMikesTeam_C
+TeamClassReferences=/Game/Libraries/Blueprints/AI/TeamSystem/Teams/MarauderTeam.MarauderTeam_C
+TeamClassReferences=/Game/Libraries/Blueprints/AI/TeamSystem/Teams/MiltiaTeam.MiltiaTeam_C
+TeamClassReferences=/Game/Libraries/Blueprints/AI/TeamSystem/Teams/NeroTeam.NeroTeam_C
+TeamClassReferences=/Game/Libraries/Blueprints/AI/TeamSystem/Teams/NewtTeam.NewtTeam_C
+TeamClassReferences=/Game/Libraries/Blueprints/AI/TeamSystem/Teams/PlayerTeam.PlayerTeam_C
+TeamClassReferences=/Game/Libraries/Blueprints/AI/TeamSystem/Teams/RagerTeam.RagerTeam_C
+TeamClassReferences=/Game/Libraries/Blueprints/AI/TeamSystem/Teams/SurvivorTeam.SurvivorTeam_C
+TeamClassReferences=/Game/Libraries/Blueprints/AI/TeamSystem/Teams/SwarmerTeam.SwarmerTeam_C
+TeamClassReferences=/Game/Libraries/Blueprints/AI/TeamSystem/Teams/WolfTeam.WolfTeam_C
+TeamClassReferences=/Game/Libraries/Blueprints/AI/TeamSystem/Teams/RIPTeam.RIPTeam_C
+TeamClassReferences=/Game/Libraries/Blueprints/AI/TeamSystem/Teams/HostageTeam.HostageTeam_C
+TeamClassReferences=/Game/Libraries/Blueprints/AI/TeamSystem/Teams/HostageTeam.HostageTeam_C
+TeamClassReferences=/Game/Libraries/Blueprints/AI/TeamSystem/Teams/LonerTeam.LonerTeam_C
+TeamClassReferences=/Game/Libraries/Blueprints/AI/TeamSystem/Teams/BreakerTeam.BreakerTeam_C
+TeamClassReferences=/Game/Libraries/Blueprints/AI/TeamSystem/Teams/BursterTeam.BursterTeam_C
+TeamClassReferences=/Game/Libraries/Blueprints/AI/TeamSystem/Teams/ScreamerTeam.ScreamerTeam_C
+TeamClassReferences=/Game/Libraries/Blueprints/AI/TeamSystem/Teams/SpitterTeam.SpitterTeam_C
+TeamClassReferences=/Game/Libraries/Blueprints/AI/TeamSystem/Teams/FreakerWolfTeam.FreakerWolfTeam_C
+TeamClassReferences=/Game/Libraries/Blueprints/AI/TeamSystem/Teams/PinnaclesTeam.PinnaclesTeam_C
+TeamClassReferences=/Game/Libraries/Blueprints/AI/TeamSystem/Teams/FreakerDeerTeam.FreakerDeerTeam_C
+TeamClassReferences=/Game/Libraries/Blueprints/AI/TeamSystem/Teams/BerserkTeam.BerserkTeam_C
+TeamClassReferences=/Game/Libraries/Blueprints/AI/TeamSystem/Teams/WizardIslandTeam.WizardIslandTeam_C
+TeamClassReferences=/Game/Libraries/Blueprints/AI/TeamSystem/Teams/DiamondLakeTeam.DiamondLakeTeam_C

[Internationalization]
+LocalizationPaths=%GAMEDIR%Content/Localization/Everything

[/Script/UnrealEd.ProjectPackagingSettings]
BuildConfiguration=PPBC_Development
StagingDirectory=(Path=)
FullRebuild=False
ForDistribution=False
IncludeDebugFiles=False
bNativizeBlueprintAssets=False
UsePakFile=True
bGenerateChunks=False
bChunkHardReferencesOnly=False
bBuildHttpChunkInstallData=False
HttpChunkInstallDataDirectory=(Path=)
HttpChunkInstallDataVersion=
IncludePrerequisites=True
IncludeCrashReporter=True
InternationalizationPreset=All
-CulturesToStage=en
+CulturesToStage=en
+CulturesToStage=ar
+CulturesToStage=cs
+CulturesToStage=da
+CulturesToStage=de
+CulturesToStage=el
+CulturesToStage=en-GB
+CulturesToStage=es
+CulturesToStage=es-419
+CulturesToStage=fi
+CulturesToStage=fr
+CulturesToStage=hr
+CulturesToStage=hu
+CulturesToStage=it
+CulturesToStage=ja
+CulturesToStage=ko
+CulturesToStage=nb
+CulturesToStage=nl
+CulturesToStage=nn
+CulturesToStage=pl
+CulturesToStage=pt
+CulturesToStage=pt-BR
+CulturesToStage=ru
+CulturesToStage=sv
+CulturesToStage=tr
+CulturesToStage=zh-Hant
DefaultCulture=en
bCookAll=False
bCookMapsOnly=False
bCompressed=False
bSkipEditorContent=False
+DirectoriesToAlwaysCook=(Path="Libraries/Scaleform")
+DirectoriesToAlwaysCook=(Path="Libraries/Tuning")
+DirectoriesToAlwaysCook=(Path="Characters/HairRendering")
+DirectoriesToAlwaysCook=(Path="Libraries/Textures/UI/Inventory")
+DirectoriesToAlwaysCook=(Path="Libraries/UI")
+DirectoriesToAlwaysCook=(Path="Libraries/Blueprints/Interacts/InventoryPickup/GameplayEffects/Consumables")
+DirectoriesToAlwaysCook=(Path="Fx/Cloth")
+DirectoriesToAlwaysCook=(Path="Weapons")
+DirectoriesToAlwaysCook=(Path="Animation/Deacon/vo")
+DirectoriesToAlwaysCook=(Path="Audio/ui")
+DirectoriesToAlwaysCook=(Path="Audio/vx/en/collectibles")
+DirectoriesToAlwaysCook=(Path="Environments/Collectables")
+DirectoriesToAlwaysCook=(Path="Maps/ORWorld/CLMX")
+DirectoriesToAlwaysCook=(Path="Libraries/DLC")
+DirectoriesToAlwaysCook=(Path="Libraries/Blueprints/Missions/MissionDataAssets/CLMX")
+DirectoriesToAlwaysStageAsUFS=(Path="Audio/_snapshots")
+DirectoriesToAlwaysStageAsUFS=(Path="Audio/_lipsync_data")
+DirectoriesToAlwaysStageAsUFS=(Path="Audio/igc/stream_data")
+DirectoriesToAlwaysStageAsUFS=(Path="Audio/music/stream_data")
+DirectoriesToAlwaysStageAsUFS=(Path="Audio/vx/en/subtitle")
+DirectoriesToAlwaysStageAsUFS=(Path="Audio/vx/en/stream_data")
+DirectoriesToAlwaysStageAsUFS=(Path="Audio/vx/en/igc/stream_data")
+DirectoriesToAlwaysStageAsUFS=(Path="Gamedata/SplineData/Game/Maps/ORWorld")
+DirectoriesToAlwaysStageAsUFS=(Path="Gamedata/SplineData/Game/Maps/ORWorldOpt")
+DirectoriesToAlwaysStageAsUFS=(Path="Gamedata/Version")
+DirectoriesToAlwaysStageAsUFS=(Path="Splash")

[/Script/MoviePlayer.MoviePlayerSettings]
bWaitForMoviesToComplete=False
bMoviesAreSkippable=True
+StartupMovies=
+StartupMovies=
+StartupMovies=
+StartupMovies=
BendMoviePlayer=(FontName="/Game/Libraries/UI/Blueprints/Fonts/DharmaGothicExpandedBold.DharmaGothicExpandedBold",LoadIconTexture=None,StudioTexture=/Game/Libraries/Textures/UI/Slate/Menus/Title/title_bendstudio_logo.title_bendstudio_logo)
